spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4406/exampledb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user
    password: userpassword
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

kafka:
  host: kafka
  port: 9094

decorator:
  datasource:
    p6spy:
      enable-logging: true