rootProject.name = 'spring-template'
include('core:core-member'
        , 'core:core-product'
        , 'core:core-outboxEvent'
        , 'core:core-payload'
        , 'core:core-inboxEvent'

        , 'api:api-member'
        , 'api:api-product'

        , 'app:app-product:app-product-kafka'

        , 'web:web-member'

        , 'batch:bill-run'
        , 'batch:bill-setup-task')