spring:
  datasource:
    username: user
    password: userpassword
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:4406/exampledb?useSSL=false
  cloud:
    task:
      initialize-enabled: false